#!/bin/sh

if [ $# -ne 3 ]; then
    echo "Usage: $0 <root directory> <number of clients> <number of nodes>"
    exit 1
fi

generate_ids() {
    env RUSTFLAGS="-A warnings" cargo run --bin generate-ids -q -- "$@"
}

ROOT_DIR=$1
N_CLIENTS=$2
N_NODES=$3

if [ $N_CLIENTS -lt 1 ] || [ $N_NODES -lt 1 ]; then
    echo "Number of clients and nodes must be at least 1."
    exit 1
fi

mkdir $ROOT_DIR || exit 1
mkdir $ROOT_DIR/pub $ROOT_DIR/priv
mkdir $ROOT_DIR/pub/clients $ROOT_DIR/pub/nodes
mkdir $ROOT_DIR/priv/clients $ROOT_DIR/priv/nodes

echo "Generating coordinator identity..."

generate_ids --cert $ROOT_DIR/pub/coord.crt --key $ROOT_DIR/priv/coord.der --subject-alt-names coord

echo "Generating client identities..."

for i in $(seq 0 $(($N_CLIENTS-1))); do
    generate_ids --cert $ROOT_DIR/pub/clients/client$i.crt --key $ROOT_DIR/priv/clients/client$i.der --subject-alt-names client$i
done

echo "Generating node identities..."

for i in $(seq 0 $(($N_NODES-1))); do
    generate_ids --cert $ROOT_DIR/pub/nodes/node$i.crt --key $ROOT_DIR/priv/nodes/node$i.der --subject-alt-names node$i
done
